/**
 * Integration Hub data (CLAUDE.md §29, §74–§95).
 * Connector health, sync status, and operational metrics for all platform integrations.
 */
import type { StatusTone } from "@/lib/types";

export type IntegrationStatus =
  | "connected"
  | "degraded"
  | "error"
  | "disconnected"
  | "scheduled";

export type IntegrationCategory =
  | "ats"
  | "vms"
  | "hris"
  | "payroll"
  | "screening"
  | "esign"
  | "communication"
  | "identity"
  | "asset"
  | "lms"
  | "shipping"
  | "accounting"
  | "crm"
  | "analytics"
  | "benefits";

export type IntegrationEvent = {
  id: string;
  timestamp: string;
  direction: "inbound" | "outbound";
  eventType: string;
  recordCount: number;
  status: "success" | "failed" | "partial" | "retrying";
  latencyMs: number;
  errorCode?: string;
  errorMessage?: string;
  retryCount: number;
  correlationId: string;
};

export type FieldMapping = {
  sourceField: string;
  targetField: string;
  transformation?: string;
  required: boolean;
  lastSynced?: string;
};

export type Integration = {
  id: string;
  name: string;
  vendor: string;
  category: IntegrationCategory;
  description: string;
  status: IntegrationStatus;
  lastSync: string;
  lastSuccess: string;
  failedRecords: number;
  successRate: number;
  avgLatencyMs: number;
  queueDepth: number;
  authExpires?: string;
  authType: "oauth2" | "api-key" | "saml" | "basic" | "mtls" | "webhook-secret";
  owner: string;
  criticality: "critical" | "high" | "medium" | "low";
  syncDirection: "inbound" | "outbound" | "bidirectional";
  syncFrequency: "real-time" | "5min" | "hourly" | "daily" | "on-demand";
  environment: "production" | "sandbox";
  dataExchanged: string[];
  recentEvents: IntegrationEvent[];
  fieldMappings: FieldMapping[];
  totalRecordsToday: number;
  totalErrorsToday: number;
  uptime30d: number;
  website?: string;
};

export const INTEGRATION_STATUS_META: Record<
  IntegrationStatus,
  { label: string; tone: StatusTone }
> = {
  connected: { label: "Connected", tone: "success" },
  degraded: { label: "Degraded", tone: "warning" },
  error: { label: "Error", tone: "danger" },
  disconnected: { label: "Disconnected", tone: "neutral" },
  scheduled: { label: "Scheduled", tone: "info" },
};

export const CATEGORY_META: Record<
  IntegrationCategory,
  { label: string; description: string }
> = {
  ats: { label: "ATS", description: "Applicant Tracking Systems" },
  vms: { label: "VMS / MSP", description: "Vendor & Contingent Labor Management" },
  hris: { label: "HRIS / HCM", description: "HR Information Systems" },
  payroll: { label: "Payroll", description: "Payroll Processing" },
  screening: { label: "Screening", description: "Background & Drug Screening" },
  esign: { label: "E-Signature", description: "Electronic Signature" },
  communication: { label: "Communications", description: "Email, SMS & Messaging" },
  identity: { label: "Identity / IAM", description: "Identity & Access Management" },
  asset: { label: "Asset Mgmt", description: "Equipment & Device Management" },
  lms: { label: "LMS", description: "Learning Management" },
  shipping: { label: "Shipping", description: "Logistics & Package Tracking" },
  accounting: { label: "Accounting / ERP", description: "Billing & Financial Systems" },
  crm: { label: "CRM", description: "Customer Relationship Management" },
  analytics: { label: "Analytics", description: "BI & Data Warehouse" },
  benefits: { label: "Benefits", description: "Benefits Administration" },
};

export const INTEGRATIONS: Integration[] = [
  // ── ATS ────────────────────────────────────────────────────────────────────
  {
    id: "int-ats-001",
    name: "JobDiva",
    vendor: "JobDiva",
    category: "ats",
    description: "Primary ATS — bidirectional sync of candidates, placements, assignments, and recruiter data driving automated onboarding package generation.",
    status: "connected",
    lastSync: "2026-06-07 14:22:00",
    lastSuccess: "2026-06-07 14:22:00",
    failedRecords: 0,
    successRate: 99.7,
    avgLatencyMs: 195,
    queueDepth: 0,
    authExpires: "2026-12-31",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Candidate", "Placement", "Assignment", "Recruiter", "Offer", "Job"],
    totalRecordsToday: 312,
    totalErrorsToday: 1,
    uptime30d: 99.8,
    website: "https://www.jobdiva.com",
    recentEvents: [
      { id: "ev-jd-001", timestamp: "2026-06-07 14:22:00", direction: "inbound", eventType: "CandidateCreated", recordCount: 3, status: "success", latencyMs: 182, retryCount: 0, correlationId: "corr-a1b2c3" },
      { id: "ev-jd-002", timestamp: "2026-06-07 14:18:00", direction: "inbound", eventType: "PlacementUpdated", recordCount: 1, status: "success", latencyMs: 210, retryCount: 0, correlationId: "corr-d4e5f6" },
      { id: "ev-jd-003", timestamp: "2026-06-07 14:05:00", direction: "outbound", eventType: "OnboardingStatusPushed", recordCount: 5, status: "success", latencyMs: 188, retryCount: 0, correlationId: "corr-g7h8i9" },
      { id: "ev-jd-004", timestamp: "2026-06-07 13:44:00", direction: "inbound", eventType: "OfferAccepted", recordCount: 2, status: "success", latencyMs: 175, retryCount: 0, correlationId: "corr-j1k2l3" },
      { id: "ev-jd-005", timestamp: "2026-06-07 13:12:00", direction: "inbound", eventType: "CandidateUpdated", recordCount: 8, status: "partial", latencyMs: 240, errorCode: "FIELD_MAP_WARN", errorMessage: "Unknown custom field skipped", retryCount: 0, correlationId: "corr-m4n5o6" },
      { id: "ev-jd-006", timestamp: "2026-06-07 12:55:00", direction: "outbound", eventType: "PackageGeneratedEvent", recordCount: 1, status: "success", latencyMs: 165, retryCount: 0, correlationId: "corr-p7q8r9" },
    ],
    fieldMappings: [
      { sourceField: "candidateId", targetField: "externalAtsId", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "firstName", targetField: "legalFirstName", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "lastName", targetField: "legalLastName", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "employmentType", targetField: "employmentClassification", transformation: "Map corp-to-corp → C2C", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "startDate", targetField: "assignmentStartDate", transformation: "Convert to UTC ISO-8601", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "clientName", targetField: "clientId", transformation: "Client name lookup", required: true, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "recruiterEmail", targetField: "recruiterId", transformation: "User email lookup", required: false, lastSynced: "2026-06-07 14:22:00" },
      { sourceField: "offerStatus", targetField: "candidateStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 14:22:00" },
    ],
  },
  {
    id: "int-ats-002",
    name: "Bullhorn",
    vendor: "Bullhorn",
    category: "ats",
    description: "Secondary ATS for staffing division — syncs candidate profiles, submissions, and placement data for automated onboarding triggers.",
    status: "connected",
    lastSync: "2026-06-07 14:15:00",
    lastSuccess: "2026-06-07 14:15:00",
    failedRecords: 0,
    successRate: 99.4,
    avgLatencyMs: 210,
    queueDepth: 0,
    authExpires: "2026-09-30",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "5min",
    environment: "production",
    dataExchanged: ["Candidate", "Submission", "Placement", "Contact", "Notes"],
    totalRecordsToday: 187,
    totalErrorsToday: 0,
    uptime30d: 99.5,
    recentEvents: [
      { id: "ev-bh-001", timestamp: "2026-06-07 14:15:00", direction: "inbound", eventType: "CandidateCreated", recordCount: 2, status: "success", latencyMs: 205, retryCount: 0, correlationId: "corr-bh001" },
      { id: "ev-bh-002", timestamp: "2026-06-07 14:10:00", direction: "inbound", eventType: "SubmissionUpdated", recordCount: 4, status: "success", latencyMs: 220, retryCount: 0, correlationId: "corr-bh002" },
      { id: "ev-bh-003", timestamp: "2026-06-07 14:05:00", direction: "outbound", eventType: "StatusSynced", recordCount: 6, status: "success", latencyMs: 190, retryCount: 0, correlationId: "corr-bh003" },
      { id: "ev-bh-004", timestamp: "2026-06-07 13:55:00", direction: "inbound", eventType: "PlacementCreated", recordCount: 1, status: "success", latencyMs: 215, retryCount: 0, correlationId: "corr-bh004" },
    ],
    fieldMappings: [
      { sourceField: "id", targetField: "externalAtsId", required: true, lastSynced: "2026-06-07 14:15:00" },
      { sourceField: "firstName", targetField: "legalFirstName", required: true, lastSynced: "2026-06-07 14:15:00" },
      { sourceField: "lastName", targetField: "legalLastName", required: true, lastSynced: "2026-06-07 14:15:00" },
      { sourceField: "employeeType", targetField: "employmentClassification", transformation: "Type enum mapping", required: true, lastSynced: "2026-06-07 14:15:00" },
      { sourceField: "dateAvailable", targetField: "assignmentStartDate", required: false, lastSynced: "2026-06-07 14:15:00" },
      { sourceField: "clientCorporation.name", targetField: "clientId", transformation: "Client name lookup", required: true, lastSynced: "2026-06-07 14:15:00" },
    ],
  },
  {
    id: "int-ats-003",
    name: "iCIMS",
    vendor: "iCIMS",
    category: "ats",
    description: "Enterprise ATS connection for a key client program — not yet configured; awaiting API credentials from client IT team.",
    status: "disconnected",
    lastSync: "—",
    lastSuccess: "—",
    failedRecords: 0,
    successRate: 0,
    avgLatencyMs: 0,
    queueDepth: 0,
    authType: "oauth2",
    owner: "Jordan Lee",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Candidate", "Job Requisition", "Offer", "Onboarding Status"],
    totalRecordsToday: 0,
    totalErrorsToday: 0,
    uptime30d: 0,
    recentEvents: [],
    fieldMappings: [
      { sourceField: "personId", targetField: "externalAtsId", required: true },
      { sourceField: "firstName", targetField: "legalFirstName", required: true },
      { sourceField: "lastName", targetField: "legalLastName", required: true },
      { sourceField: "offerStatus", targetField: "candidateStatus", required: true },
    ],
  },
  {
    id: "int-ats-004",
    name: "Greenhouse",
    vendor: "Greenhouse",
    category: "ats",
    description: "Sandbox setup in progress for tech client integration — testing candidate ingestion pipeline before production go-live.",
    status: "scheduled",
    lastSync: "2026-06-06 16:00:00",
    lastSuccess: "2026-06-06 16:00:00",
    failedRecords: 0,
    successRate: 94.0,
    avgLatencyMs: 320,
    queueDepth: 0,
    authExpires: "2026-12-01",
    authType: "api-key",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "inbound",
    syncFrequency: "hourly",
    environment: "sandbox",
    dataExchanged: ["Candidate", "Application", "Job", "Offer"],
    totalRecordsToday: 12,
    totalErrorsToday: 1,
    uptime30d: 97.2,
    recentEvents: [
      { id: "ev-gh-001", timestamp: "2026-06-06 16:00:00", direction: "inbound", eventType: "CandidateIngested", recordCount: 5, status: "success", latencyMs: 310, retryCount: 0, correlationId: "corr-gh001" },
      { id: "ev-gh-002", timestamp: "2026-06-06 15:00:00", direction: "inbound", eventType: "ApplicationUpdated", recordCount: 3, status: "failed", latencyMs: 0, errorCode: "AUTH_401", errorMessage: "API key rotation required", retryCount: 1, correlationId: "corr-gh002" },
    ],
    fieldMappings: [
      { sourceField: "id", targetField: "externalAtsId", required: true },
      { sourceField: "first_name", targetField: "legalFirstName", required: true },
      { sourceField: "last_name", targetField: "legalLastName", required: true },
      { sourceField: "applications[0].status", targetField: "candidateStatus", required: true },
    ],
  },
  {
    id: "int-ats-005",
    name: "Avionté",
    vendor: "Avionté",
    category: "ats",
    description: "Light-industrial and skilled-trade ATS — pulls candidate and assignment data for staffing division onboarding workflows.",
    status: "connected",
    lastSync: "2026-06-07 13:00:00",
    lastSuccess: "2026-06-07 13:00:00",
    failedRecords: 2,
    successRate: 96.1,
    avgLatencyMs: 415,
    queueDepth: 1,
    authExpires: "2026-11-15",
    authType: "api-key",
    owner: "Riya Kim",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Candidate", "Assignment", "Employer", "Pay Rate"],
    totalRecordsToday: 74,
    totalErrorsToday: 2,
    uptime30d: 98.1,
    recentEvents: [
      { id: "ev-av-001", timestamp: "2026-06-07 13:00:00", direction: "inbound", eventType: "CandidateUpdated", recordCount: 6, status: "success", latencyMs: 398, retryCount: 0, correlationId: "corr-av001" },
      { id: "ev-av-002", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "AssignmentCreated", recordCount: 2, status: "failed", latencyMs: 520, errorCode: "TIMEOUT_503", errorMessage: "Upstream timeout", retryCount: 2, correlationId: "corr-av002" },
      { id: "ev-av-003", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "StatusPushed", recordCount: 4, status: "success", latencyMs: 410, retryCount: 0, correlationId: "corr-av003" },
    ],
    fieldMappings: [
      { sourceField: "WorkerId", targetField: "externalAtsId", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "FirstName", targetField: "legalFirstName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "LastName", targetField: "legalLastName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "PayRate", targetField: "payRate", transformation: "Currency normalize USD", required: true, lastSynced: "2026-06-07 13:00:00" },
    ],
  },

  // ── VMS / MSP ──────────────────────────────────────────────────────────────
  {
    id: "int-vms-001",
    name: "SAP Fieldglass",
    vendor: "SAP",
    category: "vms",
    description: "Critical VMS integration — receives work orders and requisitions, returns compliance readiness and worker IDs to Fieldglass on start clearance.",
    status: "connected",
    lastSync: "2026-06-07 13:00:00",
    lastSuccess: "2026-06-07 13:00:00",
    failedRecords: 2,
    successRate: 97.8,
    avgLatencyMs: 430,
    queueDepth: 1,
    authExpires: "2026-12-01",
    authType: "oauth2",
    owner: "Jordan Lee",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Work Order", "Requisition", "Worker ID", "PO", "Bill Rate", "Compliance Status"],
    totalRecordsToday: 234,
    totalErrorsToday: 2,
    uptime30d: 99.1,
    recentEvents: [
      { id: "ev-fg-001", timestamp: "2026-06-07 13:00:00", direction: "inbound", eventType: "WorkOrderReceived", recordCount: 3, status: "success", latencyMs: 420, retryCount: 0, correlationId: "corr-fg001" },
      { id: "ev-fg-002", timestamp: "2026-06-07 12:30:00", direction: "outbound", eventType: "ComplianceStatusPushed", recordCount: 5, status: "success", latencyMs: 445, retryCount: 0, correlationId: "corr-fg002" },
      { id: "ev-fg-003", timestamp: "2026-06-07 11:45:00", direction: "inbound", eventType: "RequisitionUpdated", recordCount: 2, status: "failed", latencyMs: 610, errorCode: "RATE_429", errorMessage: "Rate limit exceeded", retryCount: 1, correlationId: "corr-fg003" },
      { id: "ev-fg-004", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "WorkerIdReturned", recordCount: 4, status: "success", latencyMs: 400, retryCount: 0, correlationId: "corr-fg004" },
    ],
    fieldMappings: [
      { sourceField: "workOrderId", targetField: "vmsWorkOrderId", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "supplierId", targetField: "vendorId", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "billRate", targetField: "billingRate", transformation: "Currency normalize USD", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "poNumber", targetField: "purchaseOrderNumber", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "costCenter", targetField: "costCenterId", required: false, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "workerStartDate", targetField: "assignmentStartDate", transformation: "Convert to UTC ISO-8601", required: true, lastSynced: "2026-06-07 13:00:00" },
    ],
  },
  {
    id: "int-vms-002",
    name: "Beeline",
    vendor: "Beeline",
    category: "vms",
    description: "Beeline VMS for enterprise client programs — syncs contingent worker data, requisitions, and start-date confirmations bidirectionally.",
    status: "connected",
    lastSync: "2026-06-07 14:00:00",
    lastSuccess: "2026-06-07 14:00:00",
    failedRecords: 0,
    successRate: 98.5,
    avgLatencyMs: 380,
    queueDepth: 0,
    authExpires: "2027-02-01",
    authType: "oauth2",
    owner: "Jordan Lee",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Requisition", "Work Order", "Candidate Submission", "Worker ID", "PO", "Cost Center"],
    totalRecordsToday: 198,
    totalErrorsToday: 0,
    uptime30d: 99.6,
    recentEvents: [
      { id: "ev-bl-001", timestamp: "2026-06-07 14:00:00", direction: "inbound", eventType: "RequisitionReceived", recordCount: 2, status: "success", latencyMs: 370, retryCount: 0, correlationId: "corr-bl001" },
      { id: "ev-bl-002", timestamp: "2026-06-07 13:30:00", direction: "outbound", eventType: "SubmissionStatusUpdated", recordCount: 3, status: "success", latencyMs: 395, retryCount: 0, correlationId: "corr-bl002" },
      { id: "ev-bl-003", timestamp: "2026-06-07 12:00:00", direction: "outbound", eventType: "WorkerStartConfirmed", recordCount: 1, status: "success", latencyMs: 360, retryCount: 0, correlationId: "corr-bl003" },
    ],
    fieldMappings: [
      { sourceField: "requisitionId", targetField: "vmsRequisitionId", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "workerId", targetField: "clientWorkerId", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "billRate", targetField: "billingRate", transformation: "Currency normalize USD", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "startDate", targetField: "assignmentStartDate", required: true, lastSynced: "2026-06-07 14:00:00" },
    ],
  },
  {
    id: "int-vms-003",
    name: "Magnit",
    vendor: "Magnit",
    category: "vms",
    description: "Magnit (formerly Workforce Logiq) MSP platform — experiencing elevated latency; webhook delivery to Magnit is intermittently failing.",
    status: "degraded",
    lastSync: "2026-06-07 12:00:00",
    lastSuccess: "2026-06-07 09:00:00",
    failedRecords: 6,
    successRate: 81.3,
    avgLatencyMs: 1240,
    queueDepth: 8,
    authExpires: "2026-08-01",
    authType: "webhook-secret",
    owner: "Jordan Lee",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Work Order", "Worker ID", "Compliance Status", "Start Date"],
    totalRecordsToday: 88,
    totalErrorsToday: 6,
    uptime30d: 93.4,
    recentEvents: [
      { id: "ev-mg-001", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "WorkOrderReceived", recordCount: 2, status: "partial", latencyMs: 1180, errorCode: "TIMEOUT_WARN", errorMessage: "Partial response; 2 records dropped", retryCount: 1, correlationId: "corr-mg001" },
      { id: "ev-mg-002", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "WebhookDeliveryFailed", recordCount: 4, status: "failed", latencyMs: 0, errorCode: "WEBHOOK_500", errorMessage: "Magnit endpoint returned 500", retryCount: 3, correlationId: "corr-mg002" },
      { id: "ev-mg-003", timestamp: "2026-06-07 10:00:00", direction: "inbound", eventType: "StatusSync", recordCount: 3, status: "success", latencyMs: 1100, retryCount: 0, correlationId: "corr-mg003" },
    ],
    fieldMappings: [
      { sourceField: "workOrderNumber", targetField: "vmsWorkOrderId", required: true, lastSynced: "2026-06-07 09:00:00" },
      { sourceField: "supplierId", targetField: "vendorId", required: true, lastSynced: "2026-06-07 09:00:00" },
      { sourceField: "startDate", targetField: "assignmentStartDate", required: true, lastSynced: "2026-06-07 09:00:00" },
    ],
  },
  {
    id: "int-vms-004",
    name: "Vndly",
    vendor: "Vndly",
    category: "vms",
    description: "Vndly VMS for a prospective client program — disconnected pending contract finalization and client IT provisioning.",
    status: "disconnected",
    lastSync: "—",
    lastSuccess: "—",
    failedRecords: 0,
    successRate: 0,
    avgLatencyMs: 0,
    queueDepth: 0,
    authType: "oauth2",
    owner: "Jordan Lee",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Requisition", "Work Order", "Worker ID", "Compliance"],
    totalRecordsToday: 0,
    totalErrorsToday: 0,
    uptime30d: 0,
    recentEvents: [],
    fieldMappings: [
      { sourceField: "workOrderId", targetField: "vmsWorkOrderId", required: true },
      { sourceField: "workerId", targetField: "clientWorkerId", required: true },
    ],
  },

  // ── HRIS / HCM ────────────────────────────────────────────────────────────
  {
    id: "int-hris-001",
    name: "Workday HCM",
    vendor: "Workday",
    category: "hris",
    description: "Enterprise HRIS — worker profiles, org structure, and manager assignments are pulled to pre-populate onboarding records. Auth token expiring soon.",
    status: "degraded",
    lastSync: "2026-06-07 06:00:00",
    lastSuccess: "2026-06-06 06:00:00",
    failedRecords: 14,
    successRate: 88.1,
    avgLatencyMs: 1100,
    queueDepth: 7,
    authExpires: "2026-07-31",
    authType: "oauth2",
    owner: "Jordan Lee",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Worker Profile", "Department", "Manager", "Legal Entity", "Location", "Employee ID"],
    totalRecordsToday: 55,
    totalErrorsToday: 14,
    uptime30d: 91.2,
    recentEvents: [
      { id: "ev-wd-001", timestamp: "2026-06-07 06:00:00", direction: "inbound", eventType: "WorkerProfileSync", recordCount: 41, status: "partial", latencyMs: 1080, errorCode: "PARTIAL_422", errorMessage: "14 records had schema mismatch on costCenter", retryCount: 0, correlationId: "corr-wd001" },
      { id: "ev-wd-002", timestamp: "2026-06-06 06:00:00", direction: "inbound", eventType: "WorkerProfileSync", recordCount: 60, status: "success", latencyMs: 1020, retryCount: 0, correlationId: "corr-wd002" },
      { id: "ev-wd-003", timestamp: "2026-06-05 06:00:00", direction: "inbound", eventType: "OrgHierarchySync", recordCount: 8, status: "success", latencyMs: 990, retryCount: 0, correlationId: "corr-wd003" },
    ],
    fieldMappings: [
      { sourceField: "workdayId", targetField: "hrmsWorkerId", required: true, lastSynced: "2026-06-07 06:00:00" },
      { sourceField: "preferredName", targetField: "preferredDisplayName", required: false, lastSynced: "2026-06-07 06:00:00" },
      { sourceField: "department.name", targetField: "departmentName", required: false, lastSynced: "2026-06-07 06:00:00" },
      { sourceField: "manager.workdayId", targetField: "managerId", required: false, lastSynced: "2026-06-07 06:00:00" },
      { sourceField: "legalEntityCode", targetField: "payrollEntityId", transformation: "Legal entity code lookup", required: true, lastSynced: "2026-06-07 06:00:00" },
      { sourceField: "costCenter", targetField: "costCenterId", required: false, lastSynced: "2026-06-06 06:00:00" },
    ],
  },
  {
    id: "int-hris-002",
    name: "UKG Pro",
    vendor: "UKG",
    category: "hris",
    description: "UKG Pro (formerly Kronos/Ultimate) for W-2 workforce — syncs timekeeping rules, overtime policies, and benefit eligibility dates.",
    status: "connected",
    lastSync: "2026-06-07 12:00:00",
    lastSuccess: "2026-06-07 12:00:00",
    failedRecords: 0,
    successRate: 98.2,
    avgLatencyMs: 540,
    queueDepth: 0,
    authExpires: "2026-10-15",
    authType: "api-key",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Worker Profile", "Timekeeping Rules", "Overtime Policy", "Benefit Eligibility"],
    totalRecordsToday: 104,
    totalErrorsToday: 0,
    uptime30d: 99.0,
    recentEvents: [
      { id: "ev-ukg-001", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "WorkerSync", recordCount: 50, status: "success", latencyMs: 525, retryCount: 0, correlationId: "corr-ukg001" },
      { id: "ev-ukg-002", timestamp: "2026-06-07 06:00:00", direction: "inbound", eventType: "TimekeepingRulesSync", recordCount: 12, status: "success", latencyMs: 540, retryCount: 0, correlationId: "corr-ukg002" },
    ],
    fieldMappings: [
      { sourceField: "employeeId", targetField: "hrmsWorkerId", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "payGroup", targetField: "payrollGroupCode", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "overtimeRule", targetField: "overtimePolicy", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "benefitEligibilityDate", targetField: "benefitsEligibleDate", required: false, lastSynced: "2026-06-07 12:00:00" },
    ],
  },
  {
    id: "int-hris-003",
    name: "ADP Workforce Now",
    vendor: "ADP",
    category: "hris",
    description: "ADP WFN — HRIS of record for mid-market clients; pulls employee classification and pushes onboarding completion status.",
    status: "connected",
    lastSync: "2026-06-07 08:00:00",
    lastSuccess: "2026-06-07 08:00:00",
    failedRecords: 1,
    successRate: 97.5,
    avgLatencyMs: 610,
    queueDepth: 0,
    authExpires: "2026-11-30",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Worker Profile", "Employment Status", "Legal Entity", "Pay Group"],
    totalRecordsToday: 78,
    totalErrorsToday: 1,
    uptime30d: 98.4,
    recentEvents: [
      { id: "ev-adpwfn-001", timestamp: "2026-06-07 08:00:00", direction: "inbound", eventType: "WorkerSync", recordCount: 39, status: "partial", latencyMs: 600, errorCode: "FIELD_MAP_WARN", errorMessage: "1 record missing positionCode", retryCount: 0, correlationId: "corr-adpwfn001" },
      { id: "ev-adpwfn-002", timestamp: "2026-06-06 08:00:00", direction: "inbound", eventType: "WorkerSync", recordCount: 40, status: "success", latencyMs: 580, retryCount: 0, correlationId: "corr-adpwfn002" },
    ],
    fieldMappings: [
      { sourceField: "associateOID", targetField: "hrmsWorkerId", required: true, lastSynced: "2026-06-07 08:00:00" },
      { sourceField: "workerType", targetField: "employmentClassification", transformation: "Type enum mapping", required: true, lastSynced: "2026-06-07 08:00:00" },
      { sourceField: "legalEntityId", targetField: "payrollEntityId", required: true, lastSynced: "2026-06-07 08:00:00" },
    ],
  },

  // ── Payroll ───────────────────────────────────────────────────────────────
  {
    id: "int-pay-001",
    name: "ADP Payroll",
    vendor: "ADP",
    category: "payroll",
    description: "Primary payroll processor — worker setup, pay rates, tax jurisdictions, and direct deposit. Currently in error state; 3 records stuck in dead-letter queue.",
    status: "error",
    lastSync: "2026-06-07 09:44:00",
    lastSuccess: "2026-06-06 18:00:00",
    failedRecords: 3,
    successRate: 71.2,
    avgLatencyMs: 880,
    queueDepth: 3,
    authExpires: "2026-08-15",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "critical",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Worker Setup", "Pay Rate", "Tax Jurisdiction", "Direct Deposit", "W-4", "Payroll Entity"],
    totalRecordsToday: 21,
    totalErrorsToday: 3,
    uptime30d: 94.8,
    recentEvents: [
      { id: "ev-adp-001", timestamp: "2026-06-07 09:44:00", direction: "outbound", eventType: "WorkerSetupFailed", recordCount: 3, status: "failed", latencyMs: 870, errorCode: "AUTH_EXPIRED", errorMessage: "OAuth token expired mid-batch; 3 records failed", retryCount: 3, correlationId: "corr-adp001" },
      { id: "ev-adp-002", timestamp: "2026-06-07 09:00:00", direction: "outbound", eventType: "DirectDepositPushed", recordCount: 4, status: "success", latencyMs: 850, retryCount: 0, correlationId: "corr-adp002" },
      { id: "ev-adp-003", timestamp: "2026-06-07 08:30:00", direction: "outbound", eventType: "TaxJurisdictionSent", recordCount: 6, status: "success", latencyMs: 910, retryCount: 0, correlationId: "corr-adp003" },
      { id: "ev-adp-004", timestamp: "2026-06-06 18:00:00", direction: "outbound", eventType: "WorkerSetupPushed", recordCount: 8, status: "success", latencyMs: 830, retryCount: 0, correlationId: "corr-adp004" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "firstName", required: true, lastSynced: "2026-06-06 18:00:00" },
      { sourceField: "legalLastName", targetField: "lastName", required: true, lastSynced: "2026-06-06 18:00:00" },
      { sourceField: "payRate", targetField: "hourlyRate", transformation: "Currency normalize USD", required: true, lastSynced: "2026-06-06 18:00:00" },
      { sourceField: "taxJurisdictionState", targetField: "stateCode", transformation: "State name → 2-letter code", required: true, lastSynced: "2026-06-06 18:00:00" },
      { sourceField: "bankRoutingNumber", targetField: "routingNumber", required: false, lastSynced: "2026-06-06 18:00:00" },
      { sourceField: "payrollEntityId", targetField: "companyCode", transformation: "Entity ID lookup", required: true, lastSynced: "2026-06-06 18:00:00" },
    ],
  },
  {
    id: "int-pay-002",
    name: "Paychex Flex",
    vendor: "Paychex",
    category: "payroll",
    description: "Paychex Flex for SMB client payroll — pushes new-hire setup and tax information; pulls payroll worker IDs on completion.",
    status: "connected",
    lastSync: "2026-06-07 13:00:00",
    lastSuccess: "2026-06-07 13:00:00",
    failedRecords: 0,
    successRate: 99.0,
    avgLatencyMs: 420,
    queueDepth: 0,
    authExpires: "2026-12-15",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Worker Setup", "Pay Rate", "Tax Information", "Payroll Worker ID"],
    totalRecordsToday: 48,
    totalErrorsToday: 0,
    uptime30d: 99.3,
    recentEvents: [
      { id: "ev-px-001", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "NewHireSetupPushed", recordCount: 5, status: "success", latencyMs: 415, retryCount: 0, correlationId: "corr-px001" },
      { id: "ev-px-002", timestamp: "2026-06-07 13:01:00", direction: "inbound", eventType: "PayrollWorkerIdReceived", recordCount: 5, status: "success", latencyMs: 388, retryCount: 0, correlationId: "corr-px002" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "firstName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "legalLastName", targetField: "lastName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "payRate", targetField: "rate", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "taxJurisdictionState", targetField: "state", required: true, lastSynced: "2026-06-07 13:00:00" },
    ],
  },
  {
    id: "int-pay-003",
    name: "Rippling",
    vendor: "Rippling",
    category: "payroll",
    description: "Rippling all-in-one HR & payroll — handles tech-client worker setup, benefits enrollment, and device provisioning in a single API call.",
    status: "connected",
    lastSync: "2026-06-07 14:00:00",
    lastSuccess: "2026-06-07 14:00:00",
    failedRecords: 0,
    successRate: 99.8,
    avgLatencyMs: 215,
    queueDepth: 0,
    authExpires: "2027-01-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Worker Setup", "Pay Rate", "Benefits", "Device Assignment"],
    totalRecordsToday: 33,
    totalErrorsToday: 0,
    uptime30d: 99.9,
    recentEvents: [
      { id: "ev-rp-001", timestamp: "2026-06-07 14:00:00", direction: "outbound", eventType: "WorkerSetupPushed", recordCount: 2, status: "success", latencyMs: 210, retryCount: 0, correlationId: "corr-rp001" },
      { id: "ev-rp-002", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "BenefitsEnrollmentTriggered", recordCount: 3, status: "success", latencyMs: 225, retryCount: 0, correlationId: "corr-rp002" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "first_name", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "legalLastName", targetField: "last_name", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "payRate", targetField: "compensation.amount", required: true, lastSynced: "2026-06-07 14:00:00" },
    ],
  },
  {
    id: "int-pay-004",
    name: "Paylocity",
    vendor: "Paylocity",
    category: "payroll",
    description: "Paylocity integration — unused since client migration to Paychex. Disconnected pending formal decommission.",
    status: "disconnected",
    lastSync: "2026-05-01 10:00:00",
    lastSuccess: "2026-05-01 10:00:00",
    failedRecords: 0,
    successRate: 0,
    avgLatencyMs: 0,
    queueDepth: 0,
    authType: "api-key",
    owner: "IT Ops",
    criticality: "low",
    syncDirection: "outbound",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Worker Setup", "Pay Rate"],
    totalRecordsToday: 0,
    totalErrorsToday: 0,
    uptime30d: 0,
    recentEvents: [],
    fieldMappings: [],
  },

  // ── Screening ─────────────────────────────────────────────────────────────
  {
    id: "int-scr-001",
    name: "HireRight",
    vendor: "HireRight",
    category: "screening",
    description: "Primary background screening vendor — orders packages, receives status updates, and triggers adjudication review tasks in real time.",
    status: "connected",
    lastSync: "2026-06-07 14:10:00",
    lastSuccess: "2026-06-07 14:10:00",
    failedRecords: 0,
    successRate: 100,
    avgLatencyMs: 350,
    queueDepth: 0,
    authExpires: "2026-11-01",
    authType: "api-key",
    owner: "Riya Kim",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Screening Order", "Consent", "Status", "Result", "Drug Test Appointment"],
    totalRecordsToday: 67,
    totalErrorsToday: 0,
    uptime30d: 99.9,
    recentEvents: [
      { id: "ev-hr-001", timestamp: "2026-06-07 14:10:00", direction: "outbound", eventType: "ScreeningOrderPlaced", recordCount: 2, status: "success", latencyMs: 345, retryCount: 0, correlationId: "corr-hr001" },
      { id: "ev-hr-002", timestamp: "2026-06-07 13:55:00", direction: "inbound", eventType: "StatusUpdated", recordCount: 4, status: "success", latencyMs: 360, retryCount: 0, correlationId: "corr-hr002" },
      { id: "ev-hr-003", timestamp: "2026-06-07 12:30:00", direction: "inbound", eventType: "ScreeningCompleted", recordCount: 1, status: "success", latencyMs: 330, retryCount: 0, correlationId: "corr-hr003" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "firstName", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "legalLastName", targetField: "lastName", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "ssn", targetField: "ssn", transformation: "Encrypted field transfer", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "screeningPackageId", targetField: "packageCode", transformation: "Package code lookup", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "vendorStatus", targetField: "screeningStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 14:10:00" },
    ],
  },
  {
    id: "int-scr-002",
    name: "Sterling",
    vendor: "Sterling",
    category: "screening",
    description: "Sterling background checks for international and specialized roles — handles multi-jurisdiction reports and professional license verification.",
    status: "connected",
    lastSync: "2026-06-07 13:45:00",
    lastSuccess: "2026-06-07 13:45:00",
    failedRecords: 0,
    successRate: 99.2,
    avgLatencyMs: 390,
    queueDepth: 0,
    authExpires: "2027-03-01",
    authType: "oauth2",
    owner: "Riya Kim",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Screening Order", "Status", "Result", "License Verification"],
    totalRecordsToday: 42,
    totalErrorsToday: 0,
    uptime30d: 99.5,
    recentEvents: [
      { id: "ev-st-001", timestamp: "2026-06-07 13:45:00", direction: "inbound", eventType: "StatusUpdated", recordCount: 3, status: "success", latencyMs: 380, retryCount: 0, correlationId: "corr-st001" },
      { id: "ev-st-002", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "OrderPlaced", recordCount: 1, status: "success", latencyMs: 400, retryCount: 0, correlationId: "corr-st002" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "first_name", required: true, lastSynced: "2026-06-07 13:45:00" },
      { sourceField: "legalLastName", targetField: "last_name", required: true, lastSynced: "2026-06-07 13:45:00" },
      { sourceField: "dateOfBirth", targetField: "dob", transformation: "Date format MM/DD/YYYY", required: true, lastSynced: "2026-06-07 13:45:00" },
      { sourceField: "vendorStatus", targetField: "screeningStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 13:45:00" },
    ],
  },
  {
    id: "int-scr-003",
    name: "First Advantage",
    vendor: "First Advantage",
    category: "screening",
    description: "First Advantage for healthcare and regulated-industry clients — elevated latency due to Advantage platform maintenance affecting status webhooks.",
    status: "degraded",
    lastSync: "2026-06-07 10:00:00",
    lastSuccess: "2026-06-07 07:00:00",
    failedRecords: 4,
    successRate: 78.5,
    avgLatencyMs: 1850,
    queueDepth: 5,
    authExpires: "2026-09-01",
    authType: "api-key",
    owner: "Riya Kim",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Screening Order", "Status", "Drug Screen", "Healthcare Credential"],
    totalRecordsToday: 28,
    totalErrorsToday: 4,
    uptime30d: 88.7,
    recentEvents: [
      { id: "ev-fa-001", timestamp: "2026-06-07 10:00:00", direction: "inbound", eventType: "WebhookDeliveryDelayed", recordCount: 4, status: "retrying", latencyMs: 1900, errorCode: "VENDOR_MAINTENANCE", errorMessage: "First Advantage platform maintenance — webhook queue backed up", retryCount: 2, correlationId: "corr-fa001" },
      { id: "ev-fa-002", timestamp: "2026-06-07 07:00:00", direction: "outbound", eventType: "OrderPlaced", recordCount: 3, status: "success", latencyMs: 1400, retryCount: 0, correlationId: "corr-fa002" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "FirstName", required: true, lastSynced: "2026-06-07 07:00:00" },
      { sourceField: "legalLastName", targetField: "LastName", required: true, lastSynced: "2026-06-07 07:00:00" },
      { sourceField: "vendorStatus", targetField: "screeningStatus", required: true, lastSynced: "2026-06-07 07:00:00" },
    ],
  },
  {
    id: "int-scr-004",
    name: "Checkr",
    vendor: "Checkr",
    category: "screening",
    description: "Checkr for gig and contractor-model clients — API-first modern screening with fast turnaround on criminal and MVR checks.",
    status: "connected",
    lastSync: "2026-06-07 14:05:00",
    lastSuccess: "2026-06-07 14:05:00",
    failedRecords: 0,
    successRate: 99.6,
    avgLatencyMs: 290,
    queueDepth: 0,
    authExpires: "2027-06-01",
    authType: "api-key",
    owner: "Riya Kim",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Screening Order", "Invitation", "Status", "Report"],
    totalRecordsToday: 51,
    totalErrorsToday: 0,
    uptime30d: 99.8,
    recentEvents: [
      { id: "ev-ck-001", timestamp: "2026-06-07 14:05:00", direction: "inbound", eventType: "ReportCompleted", recordCount: 2, status: "success", latencyMs: 285, retryCount: 0, correlationId: "corr-ck001" },
      { id: "ev-ck-002", timestamp: "2026-06-07 12:00:00", direction: "outbound", eventType: "InvitationSent", recordCount: 3, status: "success", latencyMs: 295, retryCount: 0, correlationId: "corr-ck002" },
    ],
    fieldMappings: [
      { sourceField: "legalFirstName", targetField: "first_name", required: true, lastSynced: "2026-06-07 14:05:00" },
      { sourceField: "legalLastName", targetField: "last_name", required: true, lastSynced: "2026-06-07 14:05:00" },
      { sourceField: "email", targetField: "email", required: true, lastSynced: "2026-06-07 14:05:00" },
      { sourceField: "vendorStatus", targetField: "screeningStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 14:05:00" },
    ],
  },

  // ── E-Signature ───────────────────────────────────────────────────────────
  {
    id: "int-esign-001",
    name: "DocuSign",
    vendor: "DocuSign",
    category: "esign",
    description: "Primary e-signature platform — sends envelopes for NDAs, employment agreements, and policy acknowledgments; receives signed documents back.",
    status: "connected",
    lastSync: "2026-06-07 14:00:00",
    lastSuccess: "2026-06-07 14:00:00",
    failedRecords: 0,
    successRate: 99.9,
    avgLatencyMs: 180,
    queueDepth: 0,
    authExpires: "2027-01-15",
    authType: "oauth2",
    owner: "Riya Kim",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Envelope", "Template", "Signature Status", "Signed Document", "Audit Certificate"],
    totalRecordsToday: 143,
    totalErrorsToday: 0,
    uptime30d: 99.9,
    recentEvents: [
      { id: "ev-ds-001", timestamp: "2026-06-07 14:00:00", direction: "outbound", eventType: "EnvelopeSent", recordCount: 4, status: "success", latencyMs: 175, retryCount: 0, correlationId: "corr-ds001" },
      { id: "ev-ds-002", timestamp: "2026-06-07 13:48:00", direction: "inbound", eventType: "EnvelopeSigned", recordCount: 2, status: "success", latencyMs: 188, retryCount: 0, correlationId: "corr-ds002" },
      { id: "ev-ds-003", timestamp: "2026-06-07 13:20:00", direction: "inbound", eventType: "EnvelopeDeclined", recordCount: 1, status: "success", latencyMs: 170, retryCount: 0, correlationId: "corr-ds003" },
    ],
    fieldMappings: [
      { sourceField: "candidateEmail", targetField: "signerEmail", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "legalFirstName", targetField: "signerName", transformation: "Concat first + last", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "packageDocumentId", targetField: "templateId", transformation: "Document → template mapping", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "docuSignStatus", targetField: "documentStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 14:00:00" },
    ],
  },
  {
    id: "int-esign-002",
    name: "Adobe Acrobat Sign",
    vendor: "Adobe",
    category: "esign",
    description: "Adobe Sign for client-branded agreements — used when client contracts require Adobe-native audit trails.",
    status: "connected",
    lastSync: "2026-06-07 11:00:00",
    lastSuccess: "2026-06-07 11:00:00",
    failedRecords: 0,
    successRate: 99.1,
    avgLatencyMs: 220,
    queueDepth: 0,
    authExpires: "2026-10-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Agreement", "Signature Status", "Signed Document"],
    totalRecordsToday: 32,
    totalErrorsToday: 0,
    uptime30d: 99.2,
    recentEvents: [
      { id: "ev-as-001", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "AgreementSent", recordCount: 2, status: "success", latencyMs: 215, retryCount: 0, correlationId: "corr-as001" },
      { id: "ev-as-002", timestamp: "2026-06-07 10:30:00", direction: "inbound", eventType: "AgreementSigned", recordCount: 1, status: "success", latencyMs: 228, retryCount: 0, correlationId: "corr-as002" },
    ],
    fieldMappings: [
      { sourceField: "candidateEmail", targetField: "participantEmail", required: true, lastSynced: "2026-06-07 11:00:00" },
      { sourceField: "packageDocumentId", targetField: "templateId", required: true, lastSynced: "2026-06-07 11:00:00" },
    ],
  },
  {
    id: "int-esign-003",
    name: "Dropbox Sign",
    vendor: "Dropbox",
    category: "esign",
    description: "Dropbox Sign (formerly HelloSign) — disconnected; migrated to DocuSign. Pending final decommission and data archival.",
    status: "disconnected",
    lastSync: "2026-04-15 09:00:00",
    lastSuccess: "2026-04-15 09:00:00",
    failedRecords: 0,
    successRate: 0,
    avgLatencyMs: 0,
    queueDepth: 0,
    authType: "api-key",
    owner: "IT Ops",
    criticality: "low",
    syncDirection: "bidirectional",
    syncFrequency: "on-demand",
    environment: "production",
    dataExchanged: ["Signature Request", "Signed Document"],
    totalRecordsToday: 0,
    totalErrorsToday: 0,
    uptime30d: 0,
    recentEvents: [],
    fieldMappings: [],
  },

  // ── Communications ────────────────────────────────────────────────────────
  {
    id: "int-comm-001",
    name: "Twilio SMS",
    vendor: "Twilio",
    category: "communication",
    description: "Twilio SMS for candidate nudges and OTP delivery — degraded; elevated delivery failure rate on +1 numbers affecting nudge protocol.",
    status: "degraded",
    lastSync: "2026-06-07 13:50:00",
    lastSuccess: "2026-06-07 11:00:00",
    failedRecords: 8,
    successRate: 84.3,
    avgLatencyMs: 620,
    queueDepth: 12,
    authExpires: "2026-10-01",
    authType: "api-key",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["SMS Message", "Delivery Status", "Opt-Out", "OTP"],
    totalRecordsToday: 214,
    totalErrorsToday: 8,
    uptime30d: 95.1,
    recentEvents: [
      { id: "ev-tw-001", timestamp: "2026-06-07 13:50:00", direction: "outbound", eventType: "SMSBatchFailed", recordCount: 8, status: "failed", latencyMs: 650, errorCode: "CARRIER_FILTER", errorMessage: "Carrier filtering on +1 numbers — 8 messages undelivered", retryCount: 2, correlationId: "corr-tw001" },
      { id: "ev-tw-002", timestamp: "2026-06-07 13:30:00", direction: "outbound", eventType: "OTPSent", recordCount: 12, status: "success", latencyMs: 590, retryCount: 0, correlationId: "corr-tw002" },
      { id: "ev-tw-003", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "DeliveryStatusReceived", recordCount: 20, status: "success", latencyMs: 600, retryCount: 0, correlationId: "corr-tw003" },
    ],
    fieldMappings: [
      { sourceField: "candidatePhone", targetField: "To", transformation: "Normalize to E.164", required: true, lastSynced: "2026-06-07 13:50:00" },
      { sourceField: "messageBody", targetField: "Body", required: true, lastSynced: "2026-06-07 13:50:00" },
      { sourceField: "twilioStatus", targetField: "deliveryStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 13:50:00" },
    ],
  },
  {
    id: "int-comm-002",
    name: "SendGrid Email",
    vendor: "Twilio SendGrid",
    category: "communication",
    description: "SendGrid transactional email — in error state due to expired API key; onboarding notification emails are failing to send.",
    status: "error",
    lastSync: "2026-06-07 08:00:00",
    lastSuccess: "2026-06-06 22:00:00",
    failedRecords: 22,
    successRate: 62.4,
    avgLatencyMs: 0,
    queueDepth: 22,
    authExpires: "2026-06-05",
    authType: "api-key",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Email", "Delivery Status", "Bounce", "Open Event", "Click Event"],
    totalRecordsToday: 58,
    totalErrorsToday: 22,
    uptime30d: 97.3,
    recentEvents: [
      { id: "ev-sg-001", timestamp: "2026-06-07 08:00:00", direction: "outbound", eventType: "EmailBatchFailed", recordCount: 22, status: "failed", latencyMs: 0, errorCode: "AUTH_403", errorMessage: "API key expired 2026-06-05 — all sends rejected", retryCount: 3, correlationId: "corr-sg001" },
      { id: "ev-sg-002", timestamp: "2026-06-06 22:00:00", direction: "outbound", eventType: "WelcomeEmailSent", recordCount: 18, status: "success", latencyMs: 310, retryCount: 0, correlationId: "corr-sg002" },
      { id: "ev-sg-003", timestamp: "2026-06-06 18:00:00", direction: "inbound", eventType: "DeliveryEventReceived", recordCount: 25, status: "success", latencyMs: 285, retryCount: 0, correlationId: "corr-sg003" },
    ],
    fieldMappings: [
      { sourceField: "candidateEmail", targetField: "to", required: true, lastSynced: "2026-06-06 22:00:00" },
      { sourceField: "templateId", targetField: "template_id", required: true, lastSynced: "2026-06-06 22:00:00" },
      { sourceField: "candidateName", targetField: "dynamic_template_data.name", required: true, lastSynced: "2026-06-06 22:00:00" },
    ],
  },
  {
    id: "int-comm-003",
    name: "Microsoft 365",
    vendor: "Microsoft",
    category: "communication",
    description: "Microsoft 365 for internal notifications, team alerts, and Outlook calendar integration for onboarding appointments and Day 1 scheduling.",
    status: "connected",
    lastSync: "2026-06-07 14:18:00",
    lastSuccess: "2026-06-07 14:18:00",
    failedRecords: 0,
    successRate: 100,
    avgLatencyMs: 145,
    queueDepth: 0,
    authExpires: "2027-06-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Email", "Calendar Event", "Teams Message", "User Account"],
    totalRecordsToday: 310,
    totalErrorsToday: 0,
    uptime30d: 99.9,
    recentEvents: [
      { id: "ev-m365-001", timestamp: "2026-06-07 14:18:00", direction: "outbound", eventType: "InternalAlertSent", recordCount: 6, status: "success", latencyMs: 140, retryCount: 0, correlationId: "corr-m365-001" },
      { id: "ev-m365-002", timestamp: "2026-06-07 14:00:00", direction: "outbound", eventType: "CalendarInviteSent", recordCount: 3, status: "success", latencyMs: 152, retryCount: 0, correlationId: "corr-m365-002" },
      { id: "ev-m365-003", timestamp: "2026-06-07 13:30:00", direction: "outbound", eventType: "TeamsNotificationSent", recordCount: 10, status: "success", latencyMs: 138, retryCount: 0, correlationId: "corr-m365-003" },
    ],
    fieldMappings: [
      { sourceField: "internalUserEmail", targetField: "userPrincipalName", required: true, lastSynced: "2026-06-07 14:18:00" },
      { sourceField: "messageBody", targetField: "body.content", required: true, lastSynced: "2026-06-07 14:18:00" },
    ],
  },
  {
    id: "int-comm-004",
    name: "Slack",
    vendor: "Slack",
    category: "communication",
    description: "Slack for internal ops team notifications — low-priority alerts for onboarding milestones and exception routing to ops channels.",
    status: "connected",
    lastSync: "2026-06-07 14:20:00",
    lastSuccess: "2026-06-07 14:20:00",
    failedRecords: 0,
    successRate: 99.5,
    avgLatencyMs: 110,
    queueDepth: 0,
    authExpires: "2027-03-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "low",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["Slack Message", "Alert", "Exception Notification"],
    totalRecordsToday: 88,
    totalErrorsToday: 0,
    uptime30d: 99.7,
    recentEvents: [
      { id: "ev-sl-001", timestamp: "2026-06-07 14:20:00", direction: "outbound", eventType: "ExceptionAlert", recordCount: 2, status: "success", latencyMs: 108, retryCount: 0, correlationId: "corr-sl001" },
      { id: "ev-sl-002", timestamp: "2026-06-07 14:00:00", direction: "outbound", eventType: "MilestoneNotification", recordCount: 5, status: "success", latencyMs: 112, retryCount: 0, correlationId: "corr-sl002" },
    ],
    fieldMappings: [
      { sourceField: "channelId", targetField: "channel", required: true, lastSynced: "2026-06-07 14:20:00" },
      { sourceField: "messageText", targetField: "text", required: true, lastSynced: "2026-06-07 14:20:00" },
    ],
  },

  // ── Identity / IAM ────────────────────────────────────────────────────────
  {
    id: "int-iam-001",
    name: "Okta",
    vendor: "Okta",
    category: "identity",
    description: "Primary IdP — provisions user accounts, enforces MFA, and manages SSO for all internal users and candidate portal access.",
    status: "connected",
    lastSync: "2026-06-07 14:10:00",
    lastSuccess: "2026-06-07 14:10:00",
    failedRecords: 0,
    successRate: 100,
    avgLatencyMs: 95,
    queueDepth: 0,
    authExpires: "2027-03-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "critical",
    syncDirection: "bidirectional",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["User Account", "Group", "Role", "MFA Status", "Session", "SSO Event"],
    totalRecordsToday: 185,
    totalErrorsToday: 0,
    uptime30d: 100,
    recentEvents: [
      { id: "ev-ok-001", timestamp: "2026-06-07 14:10:00", direction: "outbound", eventType: "UserProvisioned", recordCount: 3, status: "success", latencyMs: 92, retryCount: 0, correlationId: "corr-ok001" },
      { id: "ev-ok-002", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "GroupAssigned", recordCount: 3, status: "success", latencyMs: 98, retryCount: 0, correlationId: "corr-ok002" },
      { id: "ev-ok-003", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "SSOLoginEvent", recordCount: 42, status: "success", latencyMs: 90, retryCount: 0, correlationId: "corr-ok003" },
    ],
    fieldMappings: [
      { sourceField: "candidateEmail", targetField: "login", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "legalFirstName", targetField: "profile.firstName", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "legalLastName", targetField: "profile.lastName", required: true, lastSynced: "2026-06-07 14:10:00" },
      { sourceField: "personaId", targetField: "groupId", transformation: "Persona → Okta group mapping", required: true, lastSynced: "2026-06-07 14:10:00" },
    ],
  },
  {
    id: "int-iam-002",
    name: "Microsoft Entra ID",
    vendor: "Microsoft",
    category: "identity",
    description: "Entra ID (Azure AD) for client tenant provisioning — creates guest accounts and grants client portal access for approved users.",
    status: "connected",
    lastSync: "2026-06-07 13:00:00",
    lastSuccess: "2026-06-07 13:00:00",
    failedRecords: 0,
    successRate: 99.4,
    avgLatencyMs: 185,
    queueDepth: 0,
    authExpires: "2026-12-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["User Account", "Group", "License", "Guest Invitation"],
    totalRecordsToday: 42,
    totalErrorsToday: 0,
    uptime30d: 99.8,
    recentEvents: [
      { id: "ev-entra-001", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "GuestAccountCreated", recordCount: 2, status: "success", latencyMs: 180, retryCount: 0, correlationId: "corr-entra001" },
      { id: "ev-entra-002", timestamp: "2026-06-07 12:00:00", direction: "outbound", eventType: "LicenseAssigned", recordCount: 2, status: "success", latencyMs: 190, retryCount: 0, correlationId: "corr-entra002" },
    ],
    fieldMappings: [
      { sourceField: "userEmail", targetField: "userPrincipalName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "legalFirstName", targetField: "givenName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "legalLastName", targetField: "surname", required: true, lastSynced: "2026-06-07 13:00:00" },
    ],
  },
  {
    id: "int-iam-003",
    name: "Google Workspace",
    vendor: "Google",
    category: "identity",
    description: "Google Workspace for teams operating in Google-first environments — creates accounts and assigns groups during IT provisioning stage.",
    status: "connected",
    lastSync: "2026-06-07 12:00:00",
    lastSuccess: "2026-06-07 12:00:00",
    failedRecords: 0,
    successRate: 99.0,
    avgLatencyMs: 160,
    queueDepth: 0,
    authExpires: "2027-01-15",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "outbound",
    syncFrequency: "real-time",
    environment: "production",
    dataExchanged: ["User Account", "Google Group", "License", "Drive Access"],
    totalRecordsToday: 18,
    totalErrorsToday: 0,
    uptime30d: 99.5,
    recentEvents: [
      { id: "ev-gw-001", timestamp: "2026-06-07 12:00:00", direction: "outbound", eventType: "UserAccountCreated", recordCount: 2, status: "success", latencyMs: 155, retryCount: 0, correlationId: "corr-gw001" },
    ],
    fieldMappings: [
      { sourceField: "candidateEmail", targetField: "primaryEmail", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "legalFirstName", targetField: "name.givenName", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "legalLastName", targetField: "name.familyName", required: true, lastSynced: "2026-06-07 12:00:00" },
    ],
  },

  // ── Asset Management ──────────────────────────────────────────────────────
  {
    id: "int-asset-001",
    name: "ServiceNow",
    vendor: "ServiceNow",
    category: "asset",
    description: "ServiceNow ITSM — creates equipment requests, tracks provisioning workflows, and confirms device enrollment before Day 1 clearance.",
    status: "connected",
    lastSync: "2026-06-07 10:00:00",
    lastSuccess: "2026-06-07 10:00:00",
    failedRecords: 1,
    successRate: 96.5,
    avgLatencyMs: 540,
    queueDepth: 0,
    authExpires: "2026-09-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Asset Request", "Device Status", "Enrollment", "Serial Number", "Return Status"],
    totalRecordsToday: 36,
    totalErrorsToday: 1,
    uptime30d: 98.5,
    recentEvents: [
      { id: "ev-sn-001", timestamp: "2026-06-07 10:00:00", direction: "inbound", eventType: "DeviceEnrolled", recordCount: 5, status: "success", latencyMs: 530, retryCount: 0, correlationId: "corr-sn001" },
      { id: "ev-sn-002", timestamp: "2026-06-07 09:00:00", direction: "outbound", eventType: "EquipmentRequestCreated", recordCount: 2, status: "partial", latencyMs: 580, errorCode: "FIELD_MAP_WARN", errorMessage: "1 record missing assetCategory — defaulted to Laptop", retryCount: 0, correlationId: "corr-sn002" },
    ],
    fieldMappings: [
      { sourceField: "candidateId", targetField: "requestedForId", required: true, lastSynced: "2026-06-07 10:00:00" },
      { sourceField: "equipmentType", targetField: "assetCategory", required: true, lastSynced: "2026-06-07 10:00:00" },
      { sourceField: "shippingAddress", targetField: "deliveryAddress", required: true, lastSynced: "2026-06-07 10:00:00" },
      { sourceField: "serialNumber", targetField: "assetTag", required: false, lastSynced: "2026-06-07 10:00:00" },
      { sourceField: "deviceStatus", targetField: "equipmentStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 10:00:00" },
    ],
  },
  {
    id: "int-asset-002",
    name: "Microsoft Intune",
    vendor: "Microsoft",
    category: "asset",
    description: "Intune MDM — enrolls Windows devices during IT provisioning, confirms security policy compliance before Day 1 readiness is cleared.",
    status: "connected",
    lastSync: "2026-06-07 08:00:00",
    lastSuccess: "2026-06-07 08:00:00",
    failedRecords: 0,
    successRate: 98.8,
    avgLatencyMs: 480,
    queueDepth: 0,
    authExpires: "2026-12-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "inbound",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Device Enrollment", "Compliance Status", "Security Policy", "App Installation"],
    totalRecordsToday: 14,
    totalErrorsToday: 0,
    uptime30d: 99.1,
    recentEvents: [
      { id: "ev-intune-001", timestamp: "2026-06-07 08:00:00", direction: "inbound", eventType: "DeviceCompliant", recordCount: 4, status: "success", latencyMs: 475, retryCount: 0, correlationId: "corr-intune001" },
    ],
    fieldMappings: [
      { sourceField: "deviceId", targetField: "mdmDeviceId", required: true, lastSynced: "2026-06-07 08:00:00" },
      { sourceField: "complianceState", targetField: "deviceComplianceStatus", required: true, lastSynced: "2026-06-07 08:00:00" },
    ],
  },
  {
    id: "int-asset-003",
    name: "Jamf",
    vendor: "Jamf",
    category: "asset",
    description: "Jamf Pro — manages macOS/iOS device enrollment and policy enforcement for tech clients requiring Apple-first provisioning.",
    status: "connected",
    lastSync: "2026-06-07 09:00:00",
    lastSuccess: "2026-06-07 09:00:00",
    failedRecords: 0,
    successRate: 99.3,
    avgLatencyMs: 320,
    queueDepth: 0,
    authExpires: "2026-11-01",
    authType: "api-key",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "inbound",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Device Enrollment", "macOS Compliance", "App Install Status"],
    totalRecordsToday: 11,
    totalErrorsToday: 0,
    uptime30d: 99.4,
    recentEvents: [
      { id: "ev-jamf-001", timestamp: "2026-06-07 09:00:00", direction: "inbound", eventType: "DeviceEnrolled", recordCount: 2, status: "success", latencyMs: 315, retryCount: 0, correlationId: "corr-jamf001" },
    ],
    fieldMappings: [
      { sourceField: "deviceSerialNumber", targetField: "serialNumber", required: true, lastSynced: "2026-06-07 09:00:00" },
      { sourceField: "managementStatus", targetField: "deviceComplianceStatus", required: true, lastSynced: "2026-06-07 09:00:00" },
    ],
  },

  // ── Shipping ──────────────────────────────────────────────────────────────
  {
    id: "int-ship-001",
    name: "FedEx",
    vendor: "FedEx",
    category: "shipping",
    description: "FedEx shipping for equipment delivery — generates labels, tracks shipments, and triggers Day 1 readiness updates on confirmed delivery.",
    status: "connected",
    lastSync: "2026-06-07 13:00:00",
    lastSuccess: "2026-06-07 13:00:00",
    failedRecords: 0,
    successRate: 98.0,
    avgLatencyMs: 440,
    queueDepth: 0,
    authExpires: "2027-01-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Shipment", "Label", "Tracking Number", "Delivery Event", "Proof of Delivery"],
    totalRecordsToday: 28,
    totalErrorsToday: 0,
    uptime30d: 99.0,
    recentEvents: [
      { id: "ev-fdx-001", timestamp: "2026-06-07 13:00:00", direction: "inbound", eventType: "PackageDelivered", recordCount: 3, status: "success", latencyMs: 430, retryCount: 0, correlationId: "corr-fdx001" },
      { id: "ev-fdx-002", timestamp: "2026-06-07 09:00:00", direction: "outbound", eventType: "LabelCreated", recordCount: 2, status: "success", latencyMs: 455, retryCount: 0, correlationId: "corr-fdx002" },
    ],
    fieldMappings: [
      { sourceField: "shippingAddress", targetField: "recipientAddress", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "candidateName", targetField: "recipientName", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "trackingNumber", targetField: "shipmentTrackingId", required: true, lastSynced: "2026-06-07 13:00:00" },
      { sourceField: "deliveryStatus", targetField: "equipmentDeliveryStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 13:00:00" },
    ],
  },
  {
    id: "int-ship-002",
    name: "UPS",
    vendor: "UPS",
    category: "shipping",
    description: "UPS as secondary shipping carrier — used when FedEx is unavailable or client location requires UPS-specific delivery options.",
    status: "connected",
    lastSync: "2026-06-07 11:00:00",
    lastSuccess: "2026-06-07 11:00:00",
    failedRecords: 0,
    successRate: 97.5,
    avgLatencyMs: 460,
    queueDepth: 0,
    authExpires: "2027-02-01",
    authType: "oauth2",
    owner: "IT Ops",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Shipment", "Tracking Number", "Delivery Event"],
    totalRecordsToday: 8,
    totalErrorsToday: 0,
    uptime30d: 98.6,
    recentEvents: [
      { id: "ev-ups-001", timestamp: "2026-06-07 11:00:00", direction: "inbound", eventType: "PackageInTransit", recordCount: 2, status: "success", latencyMs: 455, retryCount: 0, correlationId: "corr-ups001" },
    ],
    fieldMappings: [
      { sourceField: "shippingAddress", targetField: "ShipTo.Address", required: true, lastSynced: "2026-06-07 11:00:00" },
      { sourceField: "trackingNumber", targetField: "shipmentTrackingId", required: true, lastSynced: "2026-06-07 11:00:00" },
    ],
  },

  // ── Accounting / ERP ──────────────────────────────────────────────────────
  {
    id: "int-acct-001",
    name: "NetSuite",
    vendor: "Oracle NetSuite",
    category: "accounting",
    description: "NetSuite ERP — syncs billing setup, PO validation, and invoice configuration as part of billing readiness gating before consultant start.",
    status: "connected",
    lastSync: "2026-06-07 12:00:00",
    lastSuccess: "2026-06-07 12:00:00",
    failedRecords: 0,
    successRate: 98.7,
    avgLatencyMs: 680,
    queueDepth: 0,
    authExpires: "2026-12-31",
    authType: "oauth2",
    owner: "Finance Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Client", "Vendor", "Purchase Order", "Cost Center", "Invoice Rule", "Revenue Code"],
    totalRecordsToday: 55,
    totalErrorsToday: 0,
    uptime30d: 99.2,
    recentEvents: [
      { id: "ev-ns-001", timestamp: "2026-06-07 12:00:00", direction: "inbound", eventType: "POValidated", recordCount: 4, status: "success", latencyMs: 670, retryCount: 0, correlationId: "corr-ns001" },
      { id: "ev-ns-002", timestamp: "2026-06-07 08:00:00", direction: "outbound", eventType: "BillingSetupSynced", recordCount: 8, status: "success", latencyMs: 690, retryCount: 0, correlationId: "corr-ns002" },
    ],
    fieldMappings: [
      { sourceField: "clientId", targetField: "customerId", transformation: "Client ID lookup", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "purchaseOrderNumber", targetField: "poNumber", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "billingRate", targetField: "itemRate", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "costCenterId", targetField: "department", required: false, lastSynced: "2026-06-07 12:00:00" },
    ],
  },
  {
    id: "int-acct-002",
    name: "QuickBooks",
    vendor: "Intuit",
    category: "accounting",
    description: "QuickBooks Online for SMB client billing — syncs invoice setup and client records for smaller client programs not yet migrated to NetSuite.",
    status: "connected",
    lastSync: "2026-06-07 10:00:00",
    lastSuccess: "2026-06-07 10:00:00",
    failedRecords: 0,
    successRate: 97.8,
    avgLatencyMs: 520,
    queueDepth: 0,
    authExpires: "2026-10-15",
    authType: "oauth2",
    owner: "Finance Ops",
    criticality: "medium",
    syncDirection: "outbound",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Client", "Invoice Rule", "Bill Rate"],
    totalRecordsToday: 22,
    totalErrorsToday: 0,
    uptime30d: 98.1,
    recentEvents: [
      { id: "ev-qb-001", timestamp: "2026-06-07 10:00:00", direction: "outbound", eventType: "CustomerSynced", recordCount: 3, status: "success", latencyMs: 515, retryCount: 0, correlationId: "corr-qb001" },
    ],
    fieldMappings: [
      { sourceField: "clientId", targetField: "customerId", required: true, lastSynced: "2026-06-07 10:00:00" },
      { sourceField: "billingRate", targetField: "salesItemRate", required: true, lastSynced: "2026-06-07 10:00:00" },
    ],
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    id: "int-crm-001",
    name: "Salesforce",
    vendor: "Salesforce",
    category: "crm",
    description: "Salesforce CRM — client account and contact data drives program configuration; onboarding start events push back to Salesforce opportunity records.",
    status: "connected",
    lastSync: "2026-06-07 14:00:00",
    lastSuccess: "2026-06-07 14:00:00",
    failedRecords: 0,
    successRate: 99.1,
    avgLatencyMs: 310,
    queueDepth: 0,
    authExpires: "2026-12-01",
    authType: "oauth2",
    owner: "Sales Ops",
    criticality: "high",
    syncDirection: "bidirectional",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Client Account", "Contact", "Opportunity", "Contract", "Program"],
    totalRecordsToday: 62,
    totalErrorsToday: 0,
    uptime30d: 99.5,
    recentEvents: [
      { id: "ev-sf-001", timestamp: "2026-06-07 14:00:00", direction: "inbound", eventType: "AccountSynced", recordCount: 5, status: "success", latencyMs: 305, retryCount: 0, correlationId: "corr-sf001" },
      { id: "ev-sf-002", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "OnboardingStartPushed", recordCount: 2, status: "success", latencyMs: 318, retryCount: 0, correlationId: "corr-sf002" },
    ],
    fieldMappings: [
      { sourceField: "accountId", targetField: "clientId", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "accountName", targetField: "clientName", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "ownerEmail", targetField: "accountManagerId", transformation: "User email lookup", required: false, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "contractNumber", targetField: "contractId", required: false, lastSynced: "2026-06-07 14:00:00" },
    ],
  },

  // ── Analytics / BI ────────────────────────────────────────────────────────
  {
    id: "int-analytics-001",
    name: "Snowflake",
    vendor: "Snowflake",
    category: "analytics",
    description: "Snowflake data warehouse — receives operational event streams for reporting, historical snapshots, and AI model training datasets.",
    status: "connected",
    lastSync: "2026-06-07 14:00:00",
    lastSuccess: "2026-06-07 14:00:00",
    failedRecords: 0,
    successRate: 99.3,
    avgLatencyMs: 780,
    queueDepth: 0,
    authExpires: "2027-01-01",
    authType: "oauth2",
    owner: "Data Engineering",
    criticality: "medium",
    syncDirection: "outbound",
    syncFrequency: "hourly",
    environment: "production",
    dataExchanged: ["Operational Events", "Dimension Data", "Audit Events", "Metrics", "AI Outputs"],
    totalRecordsToday: 1240,
    totalErrorsToday: 0,
    uptime30d: 99.7,
    recentEvents: [
      { id: "ev-sf2-001", timestamp: "2026-06-07 14:00:00", direction: "outbound", eventType: "EventStreamPushed", recordCount: 320, status: "success", latencyMs: 770, retryCount: 0, correlationId: "corr-snow001" },
      { id: "ev-sf2-002", timestamp: "2026-06-07 13:00:00", direction: "outbound", eventType: "EventStreamPushed", recordCount: 285, status: "success", latencyMs: 790, retryCount: 0, correlationId: "corr-snow002" },
    ],
    fieldMappings: [
      { sourceField: "eventId", targetField: "EVENT_ID", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "eventType", targetField: "EVENT_TYPE", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "timestamp", targetField: "EVENT_TS", transformation: "Convert to UTC ISO-8601", required: true, lastSynced: "2026-06-07 14:00:00" },
      { sourceField: "tenantId", targetField: "TENANT_ID", required: true, lastSynced: "2026-06-07 14:00:00" },
    ],
  },
  {
    id: "int-analytics-002",
    name: "Power BI",
    vendor: "Microsoft",
    category: "analytics",
    description: "Power BI for executive and client reporting dashboards — pulls from Snowflake via DirectQuery for near-real-time operational reports.",
    status: "connected",
    lastSync: "2026-06-07 08:00:00",
    lastSuccess: "2026-06-07 08:00:00",
    failedRecords: 0,
    successRate: 98.5,
    avgLatencyMs: 1100,
    queueDepth: 0,
    authExpires: "2026-12-01",
    authType: "oauth2",
    owner: "Data Engineering",
    criticality: "low",
    syncDirection: "inbound",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Dashboard Dataset", "Report Snapshot", "Metric"],
    totalRecordsToday: 4,
    totalErrorsToday: 0,
    uptime30d: 98.9,
    recentEvents: [
      { id: "ev-pbi-001", timestamp: "2026-06-07 08:00:00", direction: "inbound", eventType: "DatasetRefreshed", recordCount: 1, status: "success", latencyMs: 1090, retryCount: 0, correlationId: "corr-pbi001" },
    ],
    fieldMappings: [
      { sourceField: "snowflakeSchema", targetField: "datasetTable", required: true, lastSynced: "2026-06-07 08:00:00" },
    ],
  },

  // ── Benefits ──────────────────────────────────────────────────────────────
  {
    id: "int-ben-001",
    name: "Employee Navigator",
    vendor: "Employee Navigator",
    category: "benefits",
    description: "Employee Navigator — triggers benefits enrollment windows on new-hire setup completion and receives enrollment confirmation to clear benefits readiness gate.",
    status: "connected",
    lastSync: "2026-06-07 12:00:00",
    lastSuccess: "2026-06-07 12:00:00",
    failedRecords: 0,
    successRate: 98.4,
    avgLatencyMs: 560,
    queueDepth: 0,
    authExpires: "2026-11-01",
    authType: "api-key",
    owner: "Benefits Admin",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Eligibility", "Enrollment Window", "Plan Selection", "Dependent", "Enrollment Confirmation"],
    totalRecordsToday: 31,
    totalErrorsToday: 0,
    uptime30d: 98.8,
    recentEvents: [
      { id: "ev-en-001", timestamp: "2026-06-07 12:00:00", direction: "outbound", eventType: "EligibilityPushed", recordCount: 5, status: "success", latencyMs: 550, retryCount: 0, correlationId: "corr-en001" },
      { id: "ev-en-002", timestamp: "2026-06-07 12:30:00", direction: "inbound", eventType: "EnrollmentConfirmed", recordCount: 3, status: "success", latencyMs: 570, retryCount: 0, correlationId: "corr-en002" },
    ],
    fieldMappings: [
      { sourceField: "candidateId", targetField: "employeeId", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "legalFirstName", targetField: "firstName", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "legalLastName", targetField: "lastName", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "benefitsEligibleDate", targetField: "eligibilityDate", required: true, lastSynced: "2026-06-07 12:00:00" },
      { sourceField: "enrollmentStatus", targetField: "benefitsReadinessStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 12:00:00" },
    ],
  },

  // ── LMS ───────────────────────────────────────────────────────────────────
  {
    id: "int-lms-001",
    name: "Cornerstone LMS",
    vendor: "Cornerstone OnDemand",
    category: "lms",
    description: "Cornerstone LMS — assigns onboarding training courses on package activation and receives completion events to update training readiness gates.",
    status: "connected",
    lastSync: "2026-06-07 11:00:00",
    lastSuccess: "2026-06-07 11:00:00",
    failedRecords: 0,
    successRate: 97.9,
    avgLatencyMs: 490,
    queueDepth: 0,
    authExpires: "2026-12-15",
    authType: "oauth2",
    owner: "Training Ops",
    criticality: "medium",
    syncDirection: "bidirectional",
    syncFrequency: "daily",
    environment: "production",
    dataExchanged: ["Course Assignment", "Enrollment", "Completion", "Score", "Certificate"],
    totalRecordsToday: 43,
    totalErrorsToday: 0,
    uptime30d: 98.5,
    recentEvents: [
      { id: "ev-cs-001", timestamp: "2026-06-07 11:00:00", direction: "outbound", eventType: "CourseAssigned", recordCount: 6, status: "success", latencyMs: 480, retryCount: 0, correlationId: "corr-cs001" },
      { id: "ev-cs-002", timestamp: "2026-06-07 10:00:00", direction: "inbound", eventType: "CourseCompleted", recordCount: 4, status: "success", latencyMs: 500, retryCount: 0, correlationId: "corr-cs002" },
    ],
    fieldMappings: [
      { sourceField: "candidateId", targetField: "learnerId", required: true, lastSynced: "2026-06-07 11:00:00" },
      { sourceField: "trainingCourseId", targetField: "courseId", required: true, lastSynced: "2026-06-07 11:00:00" },
      { sourceField: "completionStatus", targetField: "trainingStatus", transformation: "Status enum mapping", required: true, lastSynced: "2026-06-07 11:00:00" },
    ],
  },
];

export function getIntegration(id: string): Integration | undefined {
  return INTEGRATIONS.find((i) => i.id === id);
}

export function getIntegrationsByCategory(cat: IntegrationCategory): Integration[] {
  return INTEGRATIONS.filter((i) => i.category === cat);
}

export function integrationStats(): {
  connected: number;
  degraded: number;
  errors: number;
  criticalDown: number;
  total: number;
  healthy: number;
} {
  const connected = INTEGRATIONS.filter((i) => i.status === "connected").length;
  const degraded = INTEGRATIONS.filter((i) => i.status === "degraded").length;
  const errors = INTEGRATIONS.filter((i) => i.status === "error").length;
  const criticalDown = INTEGRATIONS.filter(
    (i) =>
      i.criticality === "critical" &&
      ["error", "disconnected", "degraded"].includes(i.status),
  ).length;
  const total = INTEGRATIONS.length;
  const healthy = connected;
  return { connected, degraded, errors, criticalDown, total, healthy };
}
